Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

spots = load_sunspots()
plt.plot(spots)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[13], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m----> 3[0m spots [38;5;241m=[39m [43mload_sunspots[49m[43m([49m[43m)[49m
[1;32m      4[0m plt[38;5;241m.[39mplot(spots)

Cell [0;32mIn[12], line 21[0m, in [0;36mload_sunspots[0;34m()[0m
[1;32m     19[0m data [38;5;241m=[39m csv[38;5;241m.[39mreader(StringIO(x[38;5;241m.[39mtext))
[1;32m     20[0m [38;5;28mnext[39m(data)  [38;5;66;03m# Skip header row[39;00m
[0;32m---> 21[0m [38;5;28;01mreturn[39;00m [[38;5;28mfloat[39m(row[[38;5;241m1[39m]) [38;5;28;01mfor[39;00m row [38;5;129;01min[39;00m data]

Cell [0;32mIn[12], line 21[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m     19[0m data [38;5;241m=[39m csv[38;5;241m.[39mreader(StringIO(x[38;5;241m.[39mtext))
[1;32m     20[0m [38;5;28mnext[39m(data)  [38;5;66;03m# Skip header row[39;00m
[0;32m---> 21[0m [38;5;28;01mreturn[39;00m [[38;5;28;43mfloat[39;49m[43m([49m[43mrow[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m)[49m [38;5;28;01mfor[39;00m row [38;5;129;01min[39;00m data]

[0;31mValueError[0m: could not convert string to float: 'You have exceeded the anonymous user limit of 50 calls per day. To make more calls today, please register for a free Nasdaq Data Link account and then include your API key with your requests.'
ValueError: could not convert string to float: 'You have exceeded the anonymous user limit of 50 calls per day. To make more calls today, please register for a free Nasdaq Data Link account and then include your API key with your requests.'

